name: SFDX BUILD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!!
    - name: Run a multi-line script
      run: |
        echo Installing SFDX
        sudo su
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
        mkdir sfdx
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
        ./sfdx/install
        sfdx force:auth:jwt:grant -a paladin-packaging -u hls@paladingroup.com -f ./server.key -i 3MVG9KsVczVNcM8z8huEg2si11FMed0M_1Snx7qznMlDbRT5H2nLSBxomTYg_j6ZLYjMqIGRuexEOM6Dv1iw1 -r https://login.salesforce.com
        sfdx force:org:list --help
