name: SFDX BUILD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Installing SFDX
        sudo su
        mkdir sfdx
        tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
        ./sfdx/install
        sfdx force:auth:sfdxurl:store -f connection -a nagendra-labs
        sfdx force:org:list
        sfdx force:org:display -u nagendra@jcs.labs --verbose
